export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED'

export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS'
export const GET_CATS_FAILED = 'GET_CATS_FAILED'

export const SET_CATEGORY = 'SET_CATEGORY'